# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/kenshin-takahiro"

[social.params]
icon = "brand-github"

[[social]]
identifier = "gitlab"
name = "GitLab"
url = "https://gitlab.com/kenshin21"

[social.params]
icon = "brand-gitlab"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/kenshin_ninja"

[social.params]
icon = "brand-twitter"

[[social]]
identifier = "nostr"
name = "Nostr"
url = "https://nosta.me/npub10xxhztawwgtuapdej49q5jgfawu5p0f2j2tzuaxxww2hl546ct3sr7pcjl"

[social.params]
icon = "user"